### ISSUE TITLE
Blog images not showing up on Twitter

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/www_threefold_io#206]
![photo_2022-10-18 18 21 53](https://user-images.githubusercontent.com/50134479/196473315-e8dc644c-e874-4023-bca5-48ac8c552abf.jpeg)

Please fix asap. Thanks!

**Comment by samaradel** [comment]
![image](https://user-images.githubusercontent.com/11662805/196709136-7443689f-75df-480f-b6d3-8f6d1460c00c.png)
fixed on staging

**Comment by samtaggart** [comment]
It looks like it's an issue on some other posts too. Is there a universal fix? Or is it something that has to be done per post?

**Comment by ehab-hassan** [comment]
I think it need hard refresh can u give us example if what not working, because it apply for all

**Comment by sasha-astiadi** [comment]
@ehab-hassan @samtaggart still an issue? pls check today @ehab-hassan thank you

**Comment by ehab-hassan** [comment]
ll close this issue as I tested it in many blogs at twitter and facebook .
